<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-28T11:01:32 EET" name="Suite" finished-at="2022-02-28T11:01:44 EET" duration-ms="12212">
    <groups>
    </groups>
    <test started-at="2022-02-28T11:01:32 EET" name="Test" finished-at="2022-02-28T11:01:44 EET" duration-ms="12212">
      <class name="tests.AmazonMainPageTests2">
        <test-method is-config="true" signature="SetUpTest()[pri:0, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:32 EET" name="SetUpTest" finished-at="2022-02-28T11:01:36 EET" duration-ms="3961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpTest -->
        <test-method signature="enterProduct()[pri:0, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:36 EET" name="enterProduct" finished-at="2022-02-28T11:01:36 EET" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterProduct -->
        <test-method signature="searchProduct()[pri:1, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:36 EET" name="searchProduct" finished-at="2022-02-28T11:01:38 EET" duration-ms="2270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProduct -->
        <test-method signature="add()[pri:2, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:38 EET" name="add" finished-at="2022-02-28T11:01:40 EET" duration-ms="1724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method signature="myMethod2()[pri:3, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:40 EET" name="myMethod2" finished-at="2022-02-28T11:01:40 EET" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.AmazonMainPageTests2.myMethod2(AmazonMainPageTests2.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myMethod2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.AmazonMainPageTests2@5d7148e2]" started-at="2022-02-28T11:01:40 EET" name="tearDown" finished-at="2022-02-28T11:01:44 EET" duration-ms="4147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.AmazonMainPageTests2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
